# Generated by Django 5.2 on 2025-06-05 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntornoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre opcional para identificar el entorno de trabajo.', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el entorno.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del entorno.')),
                ('administrador', models.OneToOneField(help_text='Usuario que administra este entorno de trabajo.', on_delete=django.db.models.deletion.CASCADE, related_name='entorno_administrado', to=settings.AUTH_USER_MODEL)),
                ('colaboradores', models.ManyToManyField(blank=True, help_text='Usuarios que colaboran en este entorno de trabajo.', related_name='entornos_donde_colabora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entorno de Trabajo',
                'verbose_name_plural': 'Entornos de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
