# Generated by Django 5.2 on 2025-06-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cargar_productos', '0003_producto_entorno'),
        ('app_entornos_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_minimo', models.PositiveIntegerField(default=10, help_text='Cantidad mínima para que se muestre una alerta de stock.')),
                ('activo', models.BooleanField(default=True)),
                ('entorno_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_entornos_trabajo.entornotrabajo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app_cargar_productos.producto')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'unique_together': {('producto', 'entorno_trabajo')},
            },
        ),
    ]
