# Generated by Django 5.2 on 2025-06-05 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cargar_productos', '0002_alter_producto_options_remove_producto_usuario_id_and_more'),
        ('app_entornos_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='entorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_entornos_trabajo.entornotrabajo'),
        ),
    ]
