# Generated by Django 5.2 on 2025-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cargar_productos', '0003_producto_entorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para que aparezca en la página principal'),
        ),
    ]
